 - name: Create a ApplicationGateway
   azure_rm_applicationgateway:
     resource_group_name: my_resource_group_name
     application_gateway_name: my_application_gateway_name
     enable_http2: true
     enable_fips: true
     force_firewall_policy_association: true
   

 - name: Update the ApplicationGateway (no change)
   azure_rm_applicationgateway:
     resource_group_name: my_resource_group_name
     application_gateway_name: my_application_gateway_name
     enable_http2: true
     enable_fips: true
     force_firewall_policy_association: true
   

 - name: Update the ApplicationGateway
   azure_rm_applicationgateway:
     resource_group_name: my_resource_group_name
     application_gateway_name: my_application_gateway_name
     enable_http2: true2
     enable_fips: true2
     force_firewall_policy_association: true2
   

 - name: Delete the ApplicationGateway
   azure_rm_applicationgateway:
     resource_group_name: my_resource_group_name
     application_gateway_name: my_application_gateway_name
     state: absent
   
